add_library(geolib
    src/BritishNationalGridProjection.cpp
    src/DateTimeUtc.cpp
    src/EarthModel.cpp
    src/GeoLocation.cpp
    src/GridHeightDataSource.cpp
    src/GroundPlane.cpp
    src/HeightDataSourceRegistry.cpp
    src/HorizonDome.cpp
    src/SunPosition.cpp
    src/SunPath.cpp
    src/SunEnergy.cpp
    src/TerrainModel.cpp
    src/TriangleMesh.cpp
    src/UtmProjection.cpp
    src/data_sources/BavariaDgm1HeightDataSource.cpp
    src/data_sources/BavariaDgm1TileDownloader.cpp
    src/data_sources/BavariaDgm1TileReader.cpp
    src/data_sources/BngGridTile.cpp
    src/data_sources/WorldCopernicusDem30HeightDataSource.cpp
    src/data_sources/WorldCopernicusDem30TileDownloader.cpp
    src/data_sources/WorldCopernicusDem30TileReader.cpp
    src/data_sources/GermanyDgm5HeightDataSource.cpp
    src/data_sources/GermanyDgm5TileDownloader.cpp
    src/data_sources/GermanyDgm5TileReader.cpp
    src/data_sources/UkEaLidarHeightDataSource.cpp
    src/data_sources/UkEaLidarTileDownloader.cpp
    src/data_sources/UkEaLidarTileReader.cpp
    src/data_sources/UsaUsgs3Dep1mHeightDataSource.cpp
    src/data_sources/UsaUsgs3Dep1mTileDownloader.cpp
    src/data_sources/UsaUsgs3Dep1mTileReader.cpp
    src/data_sources/Utm32GridTile.cpp
    src/data_sources/UtmGridTile.cpp
)

target_include_directories(geolib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
