add_library(geolib
    src/BritishNationalGridProjection.cpp
    src/DateTimeUtc.cpp
    src/EarthModel.cpp
    src/GeoLocation.cpp
    src/GridHeightDataSource.cpp
    src/GroundPlane.cpp
    src/HeightDataSourceRegistry.cpp
    src/HorizonDome.cpp
    src/SolarPosition.cpp
    src/SunPath.cpp
    src/TerrainModel.cpp
    src/TriangleMesh.cpp
    src/UtmProjection.cpp
    src/data_sources/BavariaDgm1HeightDataSource.cpp
    src/data_sources/BavariaDgm1TileDownloader.cpp
    src/data_sources/BavariaDgm1TileReader.cpp
    src/data_sources/BkgDgm5HeightDataSource.cpp
    src/data_sources/BkgDgm5TileDownloader.cpp
    src/data_sources/BkgDgm5TileReader.cpp
    src/data_sources/BngGridTile.cpp
    src/data_sources/CopernicusDem30HeightDataSource.cpp
    src/data_sources/CopernicusDem30TileDownloader.cpp
    src/data_sources/CopernicusDem30TileReader.cpp
    src/data_sources/UkEaLidarHeightDataSource.cpp
    src/data_sources/UkEaLidarTileDownloader.cpp
    src/data_sources/UkEaLidarTileReader.cpp
    src/data_sources/Utm32GridTile.cpp
)

target_include_directories(geolib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
